version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres-temp
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: ufu123
      POSTGRES_DB: ufuproject
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
