CREATE TABLE tipo_perguntas (
    id_tipo INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    descricao VARCHAR(255) NOT NULL,
    PRIMARY KEY(id_tipo)
);

COMMENT ON TABLE tipo_perguntas IS 'Tabela de tipos de perguntas';
COMMENT ON COLUMN tipo_perguntas.id_tipo IS 'Identificador único do tipo de pergunta';
COMMENT ON COLUMN tipo_perguntas.descricao IS 'Descrição do tipo de pergunta'; 