CREATE TABLE usuarios (
    id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    nome VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    senha_hash VARCHAR(255) NOT NULL,
    dt_criacao TIMESTAMP,
    dt_atualizacao TIMESTAMP,
    is_ativo BOOLEAN NOT NULL DEFAULT true,
    is_admin BOOLEAN DEFAULT false,
    PRIMARY KEY(id)
);

COMMENT ON TABLE usuarios IS 'Tabela de usuários do sistema';
COMMENT ON COLUMN usuarios.id IS 'Identificador único do usuário';
COMMENT ON COLUMN usuarios.nome IS 'Nome completo do usuário';
COMMENT ON COLUMN usuarios.email IS 'Email do usuário';
COMMENT ON COLUMN usuarios.senha_hash IS 'Hash da senha do usuário';
COMMENT ON COLUMN usuarios.dt_criacao IS 'Data de criação do usuário';
COMMENT ON COLUMN usuarios.dt_atualizacao IS 'Data da última atualização do usuário';
COMMENT ON COLUMN usuarios.is_ativo IS 'Indica se o usuário está ativo';
COMMENT ON COLUMN usuarios.is_admin IS 'Indica se o usuário é administrador'; 