CREATE TABLE perguntas (
    id_perg INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    id_usuario INTEGER,
    id_tipo INTEGER NOT NULL,
    pergunta VARCHAR(255) NOT NULL,
    is_private BOOLEAN,
    id_alter_correta INTEGER,
    gabarito_txt VARCHAR(255),
    gabarito_num DECIMAL,
    gabarito_bool BOOLEAN,
    PRIMARY KEY(id_perg)
);

COMMENT ON TABLE perguntas IS 'Tabela de perguntas do sistema';
COMMENT ON COLUMN perguntas.id_perg IS 'Identificador único da pergunta';
COMMENT ON COLUMN perguntas.id_usuario IS 'Identificador do usuário que criou a pergunta';
COMMENT ON COLUMN perguntas.id_tipo IS 'Identificador do tipo da pergunta';
COMMENT ON COLUMN perguntas.pergunta IS 'Texto da pergunta';
COMMENT ON COLUMN perguntas.is_private IS 'Indica se a pergunta é privada';
COMMENT ON COLUMN perguntas.id_alter_correta IS 'Identificador da alternativa correta';
COMMENT ON COLUMN perguntas.gabarito_txt IS 'Gabarito em formato texto';
COMMENT ON COLUMN perguntas.gabarito_num IS 'Gabarito em formato numérico';
COMMENT ON COLUMN perguntas.gabarito_bool IS 'Gabarito em formato booleano'; 