CREATE TABLE alternativas (
    id_perg INTEGER NOT NULL,
    id_alter INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    correta BOOLEAN NOT NULL DEFAULT false,
    descricao VARCHAR(255) NOT NULL,
    PRIMARY KEY(id_perg, id_alter)
);

COMMENT ON TABLE alternativas IS 'Tabela de alternativas das perguntas';
COMMENT ON COLUMN alternativas.id_perg IS 'Identificador da pergunta';
COMMENT ON COLUMN alternativas.id_alter IS 'Identificador da alternativa';
COMMENT ON COLUMN alternativas.correta IS 'Indica se a alternativa é a correta';
COMMENT ON COLUMN alternativas.descricao IS 'Texto da alternativa'; 