-- Cria a tabela grupos
CREATE TABLE grupos (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"descricao" VARCHAR(255) NOT NULL,
	"path" VARCHAR(255) NOT NULL,
	"id_usuario" INTEGER,
	PRIMARY KEY("id")
);

-- Adiciona a chave estrangeira
ALTER TABLE "grupos"
ADD FOREIGN KEY("id_usuario") REFERENCES "usuarios"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;